import type { Metadata } from 'next'

import { geistMono, geistSans } from 'sm/features/shared/fonts'
import { Footer } from 'sm/features/WelcomePage/features/Footer'
import './globals.css'

export const metadata: Metadata = {
  title: 'Scrummer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`${geistMono.className}  h-screen flex flex-col justify-between`}
        >
          <main className="px-2">{children}</main>
          <Footer />
        </div>
        )
      </body>
    </html>
  )
}
